# Streamlit用のトークン（GAS側のtoken.txtと一致させてください）
GAS_TOKEN = "TpCZyuygkfTEg-HvDthqnz8I_tR_FUS0nI7onOZF3MU"

# 各GASアプリのURLをSecretsで管理
URL_TRAINING = "https://script.google.com/macros/s/AKfycbzWNeZKPqD-V4FWsZP-90kpEP7M48O7XeUqw_DNPu1kIBvAvJMmP2A0QZ9UQW0r3yxf8w/exec"
URL_FORM = "https://forms.gle/BRUbZgVGwcyvKd7v6"
URL_DRIVE = "https://drive.google.com/drive/folders/0AKWbU0VyiymNUk9PVA"
URL_WHITEBOARD = "https://script.google.com/macros/s/AKfycbyQJSMnupWXDXtkwOUxQpG8JsTvP34OUj40LLuPit8lONkxIOXWo8Mbn4sIaJXQK5a_yw/exec"
URL_RIGGING = "https://script.google.com/macros/s/AKfycbzf66ksmm7DIKxjmHeUAL34nmXHhUzoxxG7JiQ0Q9wxggLie4x_rpxO0sPDLY252Y3E/exec"
